version: "3"
services:
    megmusic:
        build: .
        volumes:
            - ./music:/megmusic/music
        environment:
            - DISCORD_API_KEY=<YOUR_API_KEY>
            - MUSIC_PATHS=/megmusic/music
